# SPDX-FileCopyrightText: 2023 Idiap Research Institute <contact@idiap.ch>
#
# SPDX-FileContributor: Jeremy Maceiras  <jeremy.maceiras@idiap.ch>
#
# SPDX-License-Identifier: GPL-3.0-only
nav_msgs/Path[] strokes
std_msgs/UInt8 drawing_zone_idx
---
nav_msgs/Path path
